# Generated by Django 5.1.6 on 2025-02-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('category', models.CharField(choices=[('frontend', 'Front-End Development'), ('databases', 'Database Management'), ('cloud', 'Cloud & Container Technologies'), ('mobile', 'Mobile Development'), ('python_ml', 'Machine Learning'), ('backend', 'Back-End Development')], max_length=20)),
            ],
        ),
    ]
